Repository SaiKumarMalve/Gator-News, pull requests merged in 2022-04, with the labels that each got.

#213 Users can be searched based on first name
  src/page/Users/Users.js
Labels: enhancement, Frontend, React

#211 Sprint3.md
  Sprint3.md
Labels: documentation

#214 Uploading images for image management
  uploads/avatars/1631272207643.jpeg
  uploads/avatars/1632436654984.jpeg
Labels: images

#215 Uploading images for image management
  uploads/avatars/Jay.jpeg
  uploads/avatars/Santosh.jpeg
  uploads/avatars/malve.jpeg
Labels: images

#216 Uploading images for image management
  uploads/banners/UFsignature-logo.png
Labels: images

#218 Home Page Tweets and CSS
  package-lock.json
  package.json
  src/assets/png/alekhya.jpeg
  src/components/ListTweets/ListTweets.js
  src/components/ListUsers/ListUsers.scss
  src/components/ListUsers/User.js
  src/page/Home/Home.js
  src/page/Home/Home.scss
  yarn.lock
Labels: Frontend, React

#221 Modified unit tests
  UnitTests/bd_test.go
  UnitTests/routers_test.go
Labels: Backend, Go, Unit Test

#219 Update Sprint3.md
  Sprint3.md
Labels: documentation, Frontend

#222 Update bd_test.go
  UnitTests/bd_test.go
Labels: Backend Testing

#224 Update Sprint3.md
  Sprint3.md
Labels: documentation

#226 Jest Unit Cases for Front End
  src/components/User/EditUserForm/EditUserForm.test.js
Labels: Frontend, React, Unit Test, Jest

#231 Jest Unit Cases for Front End
  src/page/Users/Users.test.js
Labels: Frontend, React, Unit Test, Jest

#228 Cypress Testing for Search,Edit,Follow and Unfollow
  cypress/integration/EditProfile_Cypress_Testing.js
  cypress/integration/FollowUnfollow_Cypress_Testing.js
  cypress/integration/SearchUsers_Cypress_Testing.js
  src/components/User/BannerAvatar/BannerAvatar.js
Labels: Frontend, Cypress Testing

#232 unit test cases that are required for sprint 3
  UnitTests/bd_test.go
Labels: Backend Testing

#227 Unit test cases for models
  UnitTests/models_test.go
Labels: Backend, Go, Backend Testing

#233 Update Sprint3.md
  Sprint3.md
Labels: documentation

#234 Jest Unit Cases for Front End
  src/page/Users/Users.test.js
Labels: Frontend, React, Unit Test, Jest

#247 Consult relation unit testcase
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#242 unit test cases
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#243 Test cases
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#244 Userlist unit testcase
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#245 Low relationship unit testcase
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#246 High relationship unit testcase
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#248 Testing all the API end points
  Postman/API_Testing_Postman.json
Labels: Backend, Go, Backend Testing

#261 Jest Unit Test for Error404 Page
  .DS_Store
  src/page/Error404/Error404.test.js
  src/page/Error404/__snapshots__/Error404.test.js.snap
  yarn.lock
Labels: Frontend, React, Unit Test, Jest

#263 Jest Unit Testing for Home Page
  src/page/Home/Home.test.js
  src/page/SignInSingUp/SignInSingUp.js
  src/page/SignInSingUp/SignInSingUp.test.js
  src/page/User/User.js
  src/page/User/User.test.js
  src/page/Users/Users.test.js
Labels: Frontend, React, Unit Test, Jest

#264 Jest Unit Testing for ListUsers Page
  src/components/ListUsers/ListUsers.test.js
Labels: Frontend, React, Unit Test, Jest

#265 add gator logo to home page
  src/page/SignInSingUp/SignInSingUp.scss
Labels: bug, enhancement, Frontend, React

#251 Cypress Logout Testing
  cypress.json
  cypress/integration/Logout_Cypress_Testing.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: Cypress Testing

#267 Routing to Logout-API
  src/components/LeftMenu/LeftMenu.js
Labels: React

#270 Create Sprint4.md
  Sprint4.md
Labels: documentation

#269 Creating github pages
  package.json
Labels: Frontend

#271 Update Sprint4.md
  Sprint4.md
Labels: documentation, Backend

#272 Postman Testing
  Postman/API_Testing_Postman.json
Labels: Backend, Postman, Backend Testing

#276 Update Sprint4.md
  Sprint4.md
Labels: documentation

#278 Updating Minor changes for SCSS
  src/components/Modal/ConfigModal/ConfigModal.scss
Labels: React

#280 Minor changes for the websites
  src/components/User/BannerAvatar/BannerAvatar.js
  src/page/Home/Home.js
  src/page/User/User.js
Labels: React

#285 Update Sprint4.md
  Sprint4.md
Labels: documentation, Frontend

#287 Update Sprint4.md
  Sprint4.md
Labels: documentation
