Repository SaiKumarMalve/Gator-News, pull requests merged in 2022-03, with the labels that each got.

#105 Wrote unit test cases for all the models
  models/models_test.go
Labels: Backend, Go, Backend Testing, Unit Test

#106 Live Feed for Buzz
  src/.DS_Store
  src/api/tweet.js
  src/api/user.js
  src/assets/.DS_Store
  src/assets/png/.DS_Store
  src/assets/png/avatar-no-found.png
  src/components/ListTweets/ListTweets.js
  src/utils/functions.js
Labels: Frontend, React

#107 Displaying Feed on Home Page based on User Profile
  src/components/User/BannerAvatar/BannerAvatar.js
  src/page/.DS_Store
  src/page/Home/Home.js
  src/page/Home/Home.scss
Labels: Frontend, React

#110 Wrote unit test cases for jwt package
  UnitTests/jwt_test.go
  UnitTests/models_test.go
Labels: Backend, Backend Testing, Unit Test

#114 Cypress Testing for Login Page
  cypress.json
  cypress/.eslintrc.json
  cypress/fixtures/example.json
  cypress/integration/Login_Cypress_Test.js
  package.json
Labels: Frontend, React, Cypress Testing

#115 Unit test cases for Routers
  UnitTests/routers_test.go
Labels: Backend, Go, Backend Testing

#118 These are the unit test cases for middlew
  UnitTests/middlew_test.go
Labels: Backend, Go, Backend Testing

#119 Wrote the unit test cases for bd package
  UnitTests/bd_test.go
Labels: Go, Backend Testing, Unit Test

#120 Build and Test Go code
  .github/workflows/go-build.yml
  .github/workflows/go-test.yml
  .github/workflows/go.yml
Labels: Backend, Go

#131 Jest Unit Test for Sign Up
  package-lock.json
  package.json
  src/App.test.js
  src/components/SignUpForm/SignUpForm.js
  src/components/SignUpForm/SignUpForm.test.js
  src/page/SignInSingUp/SignInSingUp.js
  yarn.lock
Labels: Frontend, React, Unit Test, Jest

#132 Banner Avatar Component Jest Unit Testing
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.test.js
  src/components/User/InfoUser/InfoUser.test.js
Labels: Frontend, React, Unit Test, Jest

#136 Create sprint2.md
  sprint2.md
Labels: documentation

#137 TweetModal Unit Tests
  src/components/Modal/TweetModal/TweetModal.js
  src/components/Modal/TweetModal/TweetModal.test.js
  src/components/Modal/TweetModal/__snapshots__/TweetModal.test.js.snap
Labels: Frontend, React, Unit Test, Jest

#138 Basic Modal Unit Tests
  src/components/Modal/BasicModal/BasicModal.js
  src/components/Modal/BasicModal/BasicModal.test.js
Labels: Frontend, React, Unit Test, Jest

#140 List Posts unit test using jest
  cypress/integration/Buzz_Cypress_Testing.js
  src/components/ListTweets/ListTweet.test.js
Labels: Unit Test, Jest

#141 Left menu unit tests using jest
  src/components/LeftMenu/left_menu.test.js
Labels: Unit Test, Jest

#144 Update sprint2.md
  sprint2.md
Labels: documentation

#145 Update sprint2.md
  sprint2.md
Labels: documentation, Frontend

#147 Update sprint2.md
  sprint2.md
Labels: documentation, Frontend

#148 Update sprint2.md
  sprint2.md
Labels: documentation

#149 Update sprint2.md
  sprint2.md
Labels: documentation, Backend

#150 Adding comments to functions
  bd/checkUserAlreadyExists.go
  bd/encryptPassword.go
  jwt/jwt.go
  middlew/checkBD.go
  routers/recordPost.go
  routers/registration.go
Labels: Backend, Go

#158 Deleting Posts
  bd/deletePost.go
  handlers/handlers.go
  routers/removePost.go
Labels: Backend, Go

#160 Update README.md
  README.md
Labels: documentation

#159 Profile picture
  bd/profileLookup.go
  handlers/handlers.go
  routers/getAvatar.go
  routers/getBanner.go
  routers/uploadAvatar.go
  routers/uploadBanner.go
Labels: Backend, Go, MongoDB

#161 HighRelationship registers the relationship between users
  bd/insertRelationship.go
  handlers/handlers.go
  models/relationship.go
  routers/highRelationship.go
Labels: Backend, Go

#162 LowRelationship performs the deletion of the relationship between users
  bd/deleteRelationship.go
  handlers/handlers.go
  routers/lowRelationship.go
Labels: Backend, Go

#168 Edit Porfile Form Creation
  src/components/Modal/ConfigModal/ConfigModal.js
  src/components/Modal/ConfigModal/ConfigModal.scss
  src/components/Modal/ConfigModal/index.js
  src/components/User/BannerAvatar/BannerAvatar.js
Labels: Frontend, React

#170 Added Form Layout to Edit Profile Button and Created EditProfile Layout under User
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/EditUserForm/EditUserForm.js
  src/components/User/EditUserForm/EditUserForm.scss
  src/components/User/EditUserForm/index.js
Labels: Frontend, React

#173 Added Styles to the Form
  src/components/Modal/ConfigModal/ConfigModal.scss
  src/components/User/EditUserForm/EditUserForm.scss
Labels: Frontend, React

#174 Added consult relation API
  bd/consultRelation.go
  handlers/handlers.go
  models/relationship.go
  models/requestConsultRelation.go
  routers/consultRelation.go
  routers/highRelationship.go
  routers/lowRelationship.go
Labels: Backend, Go, MongoDB

#175 Added Date Picker
  package.json
  src/components/Modal/ConfigModal/ConfigModal.scss
  src/components/User/EditUserForm/EditUserForm.js
  src/index.js
  yarn.lock
Labels: Frontend, React

#177 Updating User Cover Photo
  package-lock.json
  package.json
  src/components/User/EditUserForm/EditUserForm.js
  src/components/User/EditUserForm/EditUserForm.scss
  yarn.lock
Labels: Frontend, React

#179 Updating the Cover Photo with new image and showing a preview
  src/components/User/EditUserForm/EditUserForm.js
  src/components/User/EditUserForm/EditUserForm.scss
Labels: Frontend, React

#183 Updating user profile picture
  src/components/User/EditUserForm/EditUserForm.js
  src/components/User/EditUserForm/EditUserForm.scss
  src/utils/Icons.js
Labels: Frontend, React

#184 Edit Profile-Updating the user profile picture and cover photo in databaase
  src/api/user.js
  src/components/ListTweets/ListTweets.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/EditUserForm/EditUserForm.js
Labels: Frontend, React

#186 Edit Profile-Update User Details in Database
  src/components/User/EditUserForm/EditUserForm.js
Labels: Frontend, React

#192 Follower System
  src/api/follow.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
Labels: Frontend, React

#197 Reading all the posts from followers
  bd/readFollowersPosts.go
  handlers/handlers.go
  models/returnFollowerPosts.go
  routers/readPostRelations.go
Labels: Backend, Go, MongoDB

#198 fixed the bugs in the branch
  bd/readFollowersPosts.go
  handlers/handlers.go
  routers/readFollowersPosts.go
Labels: bug, Backend, Go, MongoDB

#201 fixed the memory location not found error
  bd/readFollowersPosts.go
Labels: Backend

#202 Fixed readFollowersPosts API issue
  bd/readFollowersPosts.go
  models/returnFollowerPosts.go
Labels: Backend, Go

#199 Getting the users list on user page
  src/api/follow.js
  src/api/tweet.js
  src/components/LeftMenu/LeftMenu.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
  src/page/Users/Users.js
  src/page/Users/Users.scss
  src/page/Users/index.js
  src/routes/Routing.js
  src/routes/configRouting.js
Labels: Frontend, React

#196 User Page Structure
  src/components/LeftMenu/LeftMenu.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
  src/page/Users/Users.js
  src/page/Users/Users.scss
  src/page/Users/index.js
  src/routes/Routing.js
  src/routes/configRouting.js
Labels: Frontend, React

#204 Fixed the consult Relationship API
  bd/consultRelation.go
Labels: Backend, Go, MongoDB

#203 Component to render users information
  package-lock.json
  package.json
  src/components/LeftMenu/LeftMenu.js
  src/components/ListUsers/ListUsers.js
  src/components/ListUsers/ListUsers.scss
  src/components/ListUsers/index.js
  src/page/Users/Users.js
  src/routes/configRouting.js
  yarn.lock
Labels: Frontend, React

#205 Show followers and new users details
  package-lock.json
  package.json
  src/api/tweet.js
  src/components/ListUsers/ListUsers.js
  src/components/ListUsers/ListUsers.scss
  src/components/ListUsers/User.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
  src/page/Users/Users.js
  yarn.lock
Labels: Frontend, React
