Repository SaiKumarMalve/Gator-News, pull requests merged in 2022-02, with the labels that each got.

#42 userRegistration CSS file
  src/components/SignUpForm/SignUpForm.scss
Labels: Frontend, React

#46 Removed Initial Value Default Values
  src/components/SignInForm/SignInForm.js
Labels: Frontend, React

#44 Login Validation
  bd/tryLogin.go
  handlers/handlers.go
  models/answerLogin.go
  routers/login.go
Labels: Backend, Go, MongoDB

#43 JSON web token validation generated during login
  jwt/jwt.go
  middlew/validJWT.go
  models/claim.go
  models/user.go
  routers/processToken.go
Labels: Backend, Go

#51 Registration Validation
  .DS_Store
  package.json
  src/App.js
  src/components/SignUpForm/SignUpForm.js
  src/index.js
  src/utils/validations.js
  yarn.lock
Labels: Frontend, React

#52 Update checkUserAlreadyExists.go
  bd/checkUserAlreadyExists.go
Labels: Backend

#54 Validating Registration page and integrating with registration API
  package-lock.json
  package.json
  src/api/auth.js
  src/components/SignInForm/SignInForm.js
  src/components/SignUpForm/SignUpForm.js
  src/utils/constant.js
  yarn.lock
Labels: Frontend, React

#56 Changes for Validation Login Page
  src/components/SignInForm/SignInForm.js
Labels: Frontend, React

#57 Added LoginApi Endpoint and used the Rest API to validate login request
  src/api/auth.js
  src/components/SignInForm/SignInForm.js
Labels: Frontend, React

#60 Added Login Token generated from API to local storage
  src/components/SignInForm/SignInForm.js
Labels: Frontend, React

#63 Reload component when user logs In, redirect to next Page
  src/App.js
  src/components/SignInForm/SignInForm.js
  src/page/SignInSingUp/SignInSingUp.js
Labels: Frontend, React

#65 Login API testing
  Postman/API_Testing_Postman.json
Labels: Postman, Backend Testing

#66 Created Routing System for Home page and re-routing for other pages
  package.json
  src/App.js
  src/page/Error404/Error404.js
  src/page/Error404/Error404.scss
  src/page/Error404/index.js
  src/page/Home/Home.js
  src/page/Home/Home.scss
  src/page/Home/index.js
  src/routes/Routing.js
  src/routes/configRouting.js
  yarn.lock
Labels: Frontend, React

#68 Created Layout System
  src/layout/BasicLayout/BasicLayout.js
  src/layout/BasicLayout/BasicLayout.scss
  src/layout/BasicLayout/index.js
  src/page/Home/Home.js
Labels: Frontend, React

#71 Left menu
  package-lock.json
  src/assets/png/UF.png
  src/assets/png/logo.png
  src/components/LeftMenu/LeftMenu.js
  src/components/LeftMenu/LeftMenu.scss
  src/components/LeftMenu/index.js
  src/index.scss
  src/layout/BasicLayout/BasicLayout.js
  src/layout/BasicLayout/BasicLayout.scss
  src/page/Home/Home.js
  src/page/Home/Home.scss
  yarn.lock
Labels: Frontend, React

#76 Creating User Profiles and Page Routing for Profiles
  package-lock.json
  package.json
  src/App.js
  src/components/LeftMenu/LeftMenu.js
  src/hooks/useAuth.js
  src/layout/BasicLayout/BasicLayout.js
  src/page/Home/Home.js
  src/page/User/User.js
  src/page/User/User.scss
  src/page/User/index.js
  src/routes/Routing.js
  src/routes/configRouting.js
  yarn.lock
Labels: Frontend, React

#77 User Profile Creation
  src/api/user.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
  src/components/User/BannerAvatar/index.js
  src/components/User/InfoUser/InfoUser.js
  src/components/User/InfoUser/InfoUser.scss
  src/components/User/InfoUser/index.js
  src/page/User/User.js
  src/page/User/User.scss
Labels: Frontend, React

#79 Updated the Postman API testing json file
  Postman/API_Testing_Postman.json
Labels: Postman, Backend Testing

#78 Modifying the profile of the user
  bd/modifyRecord.go
  handlers/handlers.go
  routers/modifyProfile.go
Labels: Backend, Go, MongoDB

#83 Testing the modify profile API
  Postman/API_Testing_Postman.json
Labels: Postman, Backend Testing

#86 Created profile page
  package.json
  src/assets/png/logo.png
  src/assets/png/user.png
  src/components/LeftMenu/LeftMenu.js
  src/components/LeftMenu/LeftMenu.scss
  src/components/Modal/TweetModal/TweetModal.js
  src/components/Modal/TweetModal/TweetModal.scss
  src/components/Modal/TweetModal/index.js
  src/components/User/BannerAvatar/BannerAvatar.js
  src/components/User/BannerAvatar/BannerAvatar.scss
  src/components/User/InfoUser/InfoUser.js
  src/layout/BasicLayout/BasicLayout.js
  src/page/User/User.js
  src/utils/Icons.js
  yarn.lock
Labels: Frontend, React

#84 Backend accomplishments for the sprint
  Sprint1.md
Labels: documentation

#87 Insert post
  bd/insertPost.go
  handlers/handlers.go
  models/post.go
  models/recordPost.go
  routers/recordPost.go
Labels: Backend, Go, MongoDB

#89 Update insertRegistration.go
  bd/insertRegistration.go
Labels: Backend, MongoDB

#91 Updated the API testing file with POST
  Postman/API_Testing_Postman.json
Labels: Postman, Backend Testing

#94 Update insertRegistration.go
  bd/insertRegistration.go
Labels: Backend, Go
