Repository SaiKumarMalve/Gator-News, pull requests merged in 2022-01, with the labels that each got.

#2 go.mod file
  go.mod
Labels: Backend, Modules

#1 Main go file
  main.go
Labels: Backend, Go

#3 added necessary mongoDB jwt drivers
  go.mod
  go.sum
Labels: Modules, MongoDB

#8 Connected to Database
  bd/connectionBD.go
Labels: Backend, Go, MongoDB

#16 User Model has been created
  models/user.go
Labels: Backend, Go

#18 Handling POST requests
  handlers/handlers.go
  middlew/checkBD.go
Labels: Backend, Go, MongoDB

#19 Left side modules
  package.json
  src/assets/png/.DS_Store
  src/assets/png/main-logo.png
  src/page/SignInSingUp/SignInSingUp.js
  src/page/SignInSingUp/SignInSingUp.scss
  src/scss/_colors.scss
  src/scss/index.scss
  yarn-error.log
  yarn.lock
Labels: Frontend, React

#21 Added Components for Login and Register on Right Component
  package-lock.json
  package.json
  src/assets/png/animation.json
  src/assets/png/gator-logo.png
  src/assets/png/main-logo.png
  src/components/Modal/BasicModal/BasicModal.js
  src/components/Modal/BasicModal/BasicModal.scss
  src/components/Modal/BasicModal/index.js
  src/page/SignInSingUp/SignInSingUp.js
  src/page/SignInSingUp/SignInSingUp.scss
  yarn.lock
Labels: Frontend, React

#20 User registration and inserting to DB
  bd/checkUserAlreadyExists.go
  bd/encryptPassword.go
  bd/insertRegistration.go
  routers/registration.go
Labels: Backend, Go, MongoDB

#28 Created basic modal for registration page
  package-lock.json
  src/components/Modal/BasicModal/BasicModal.js
  src/components/Modal/BasicModal/BasicModal.scss
  src/page/SignInSingUp/SignInSingUp.js
  src/page/SignInSingUp/SignInSingUp.scss
  yarn.lock
Labels: Frontend, React

#33 UserRegistration Form Modal
  src/components/SignUpForm/SignUpForm.js
  src/components/SignUpForm/SignUpForm.scss
  src/components/SignUpForm/index.js
  src/page/SignInSingUp/SignInSingUp.js
Labels: Frontend, React

#34 Registration API testing
  Postman/API_Testing_Postman.json
Labels: Backend, Postman

#36 Updated content in Registration Modal
  src/components/SignUpForm/SignUpForm.js
Labels: Frontend, React

#38 Login Form Modal (Popup and Components)
  .gitignore
  src/components/SignInForm/SignInForm.js
  src/components/SignInForm/SignInForm.scss
  src/components/SignInForm/index.js
  src/page/SignInSingUp/SignInSingUp.js
Labels: Frontend, React

#41 LoginFormComponents
  src/components/SignInForm/SignInForm.js
  src/components/SignInForm/SignInForm.scss
Labels: Frontend, React
